<a href="https://colab.research.google.com/github/sanahk497-sketch/10_SanahKhan_D2/blob/main/Working_with_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
n=int(input("Enter the number"))
sum=0
x=0

while(n>0):
  x = n%10
  sum= sum+x
  n=int(n/10)


print(sum)

Enter the number56
11


In [2]:
def Rev_num(n) :
  rev=0
  x=0
  while(n>0):
    y=n%10
    x=x*10+y
    n=int(n/10)
  print(x)
n=int(input("Enter The number :"))
Rev_num(n)

Enter The number :523
325


In [3]:
%%writefile sanah.cpp
#include<iostream>
using namespace std;
int main(){
  cout<<"Hello I am sanah khan"<<endl;
  return 0;

}

Writing sanah.cpp


In [4]:
!g++ sanah.cpp -o sanah
!./sanah

Hello I am sanah khan


In [5]:
!g++ sanah.cpp -o sanah_executable

In [6]:
!./sanah

Hello I am sanah khan


In [7]:
print("Hello I am sanah khan")

Hello I am sanah khan


Pallidrom code

In [8]:
def pallindrom(n):
  original=n
  rev=0

  while(n>0):
    rem=n%10
    rev=rev*10+rem
    n=n//10

  if(original==rev):
    print("Number is pallindrom")
  else:
    print("Number is not pallindrom")

n=int(input("Enter the number"))
pallindrom(n)

Enter the number456654
Number is pallindrom


In [10]:
l=[1,2,3,4,5]

# Handle edge cases for empty or single-element lists
if len(l) < 2:
    print("List must contain at least two elements to find a second maximum.")
else:
    max1 = float('-inf') # Initialize first maximum to negative infinity
    max2 = float('-inf') # Initialize second maximum to negative infinity

    for num in l:
        if num > max1:
            max2 = max1 # Current max1 becomes new max2
            max1 = num  # Current num becomes new max1
        elif num > max2 and num != max1: # If num is smaller than max1 but greater than max2
            max2 = num

    if max2 == float('-inf'):
        print("No distinct second maximum found (e.g., all elements are the same).")
    else:
        print(f"The second largest element is: {max2}")

The second largest element is: 4


In [11]:
l=[1]

# Validate that all elements are integers
for num in l:
    if not isinstance(num, int):
        print(f"Error: List contains non-integer value '{num}'. Please provide a list of integers only.")
        # You could also raise an error here: raise ValueError("List must contain only integers")
        exit() # Exits the current execution if a non-integer is found

# Handle edge cases for empty or single-element lists
if len(l) < 2:
    print("List must contain at least two elements to find a second maximum.")
else:
    max1 = 0
    max2 = -1

    for num in l:
        if num > max1:
            max2 = max1
            max1 = num
        elif num > max2 and num != max1:
            max2 = num

    if max2 == -1:
        print(max2)
    else:
        print(f"The second largest element is: {max2}")

List must contain at least two elements to find a second maximum.


In [12]:
def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers"
    elif n == 0:
        return 1
    else:
        fact = 1
        for i in range(1, n + 1):
            fact = fact * i
        return fact

# Example usage:
num = 5
print(f"The factorial of {num} is {factorial(num)}")

num = 0
print(f"The factorial of {num} is {factorial(num)}")

um = -3
print(f"The factorial of {num} is {factorial(num)}")

The factorial of 5 is 120
The factorial of 0 is 1
The factorial of 0 is 1


In [13]:
%%writefile sum.cpp
#include<iostream>
using namespace std;
int main(){
    int a,b,sum;
    a=45;
    b=54;

    cout<<"enter the sum of two no. :";
    sum =a+b;
    cout<<"sum: "<<sum;
    return 0;
}

Writing sum.cpp


In [14]:
%%writefile sum.cpp
#include<iostream>
using namespace std;
int main(){
  int n=7;
  if(n%2==0)
  cout<<"even";
  else
  cout<<"odd";
  return 0;
}

Overwriting sum.cpp


In [15]:
!g++ sum.cpp -o sum
!./sum

odd

In [16]:
n = 7
if n % 2 == 0:
  print("even")
else:
  print("odd")

odd


In [17]:
%%writefile sum.cpp
#include<iostream>
using namespace std;
int main(){
  int a,b;
  a =20;
  b =34;
  if(a>b)
  cout<<"a is larger";
  else
  cout<<"b is larger";
  return 0;

}

Overwriting sum.cpp


In [18]:
!g++ sum.cpp -o sum
!./sum

b is larger

In [19]:
a = 20
b = 34
if a > b:
  print("a is larger")
else:
  print("b is larger")

b is larger


In [21]:
!g++ sum.cpp -o sum
!./sum

b is larger

In [22]:
a = 45
b = 54

sum_val = a + b

print("enter the sum of two no. :")
print(f"sum: {sum_val}")

enter the sum of two no. :
sum: 99


In [23]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [24]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [25]:
np.array([1.5,2.5])


array([1.5, 2.5])

In [26]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [27]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [28]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [31]:
np.random.randint(0,100,(3,3))

array([[64,  2, 62],
       [ 4, 93, 55],
       [74, 15, 44]])

In [32]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a4=np.array(3)
print(a3.shape)
print(a2.size)



(2, 2, 2)
12


In [34]:
a3.ndim

3

In [35]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)

int32
float64
int64
int64
